using System;

namespace Octodiff.Tests.Util
{

    public static class Helpers
    {
        // this is a self-signed x509 cert generated by OpenSSL. Ingore the fact that it's a certificate; Used as test data because x509 is full of weird binary data values, increasing our likelihood of catching signed/unsigned mismatch bugs. 
        public static readonly byte[] TestData =
            Convert.FromBase64String(
                "MIICBDCCAaugAwIBAgIUGNg/B3GL5BId8KGNdhD6+NejvsQwCgYIKoZIzj0EAwIwWDELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxFzAVBgNVBAoMDk9jdG9wdXMgRGVwbG95MQwwCgYDVQQLDANSJkQxDTALBgNVBAMMBFRFU1QwHhcNMjMwMzIwMDk0ODQyWhcNMjQwMzE5MDk0ODQyWjBYMQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEXMBUGA1UECgwOT2N0b3B1cyBEZXBsb3kxDDAKBgNVBAsMA1ImRDENMAsGA1UEAwwEVEVTVDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFBLdySNg+Lj4gm7sil6Dk0k/0Xnnv+I3RZeZBmumFEtq9IhnaRuk9f/mNWhy4AxSlfzfQkx7PfzvUvOISz9LLqjUzBRMB0GA1UdDgQWBBS63SeKMeASd2r7/aTq2P3OkE8O/DAfBgNVHSMEGDAWgBS63SeKMeASd2r7/aTq2P3OkE8O/DAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0cAMEQCIFmc75IBFbZKfQvH3lWoS7p/Be54uekDr3y1K0pdzI6iAiAGV1RF2rnCEyWkjeO9fOUaNGEgFadGSHh8en4DJkU3cA==");

        // courtesy https://stackoverflow.com/a/9995303/234
        public static byte[] ToByteArray(this string hex)
        {
            if (hex.Length % 2 == 1)
                throw new Exception("The binary key cannot have an odd number of digits");

            byte[] arr = new byte[hex.Length >> 1];

            for (int i = 0; i < hex.Length >> 1; ++i)
            {
                arr[i] = (byte)((GetHexVal(hex[i << 1]) << 4) + (GetHexVal(hex[(i << 1) + 1])));
            }

            return arr;
        }

        static int GetHexVal(char hex)
        {
            int val = hex;
            //For uppercase A-F letters:
            //return val - (val < 58 ? 48 : 55);
            //For lowercase a-f letters:
            //return val - (val < 58 ? 48 : 87);
            //Or the two combined, but a bit slower:
            return val - (val < 58 ? 48 : (val < 97 ? 55 : 87));
        }
    }
}